# Generated by Django 5.1.15 on 2025-12-08 08:42

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notepage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
