# Generated by Django 5.1.15 on 2025-12-08 08:48

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_notepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notepage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title'}), 1: ('wagtail.blocks.RichTextBlock', (), {})}),
        ),
    ]
