# Generated by Django 5.1.15 on 2025-12-08 09:07

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_notepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notepage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('table', 2)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title'}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.contrib.table_block.blocks.TableBlock', (), {})}),
        ),
        migrations.AlterField(
            model_name='notescontentspage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, default='poo'),
            preserve_default=False,
        ),
    ]
