# Generated by Django 5.1.15 on 2025-12-08 10:06

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_notepage_body_alter_notescontentspage_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notepage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('table', 2)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title'}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('notes.blocks.BootstrapTableBlock', (), {})}),
        ),
    ]
