# Generated by Django 5.1.15 on 2025-12-12 11:21

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_alter_notepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notepage',
            name='body',
            field=wagtail.fields.StreamField([('paragraph', 0), ('table', 1)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('notes.blocks.BootstrapTableBlock', (), {})}),
        ),
    ]
