# Generated by Django 5.1.15 on 2025-12-08 10:16

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='linked_pages',
            field=wagtail.fields.StreamField([('card', 3)], blank=True, block_lookup={0: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['notes.NotesContentsPage', 'notes.NotePage'], 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': "Override the page's title.", 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('page', 0), ('custom_title', 1), ('card_image', 2)]], {'label': 'Link Card'})}),
        ),
    ]
